### ISSUE TITLE
Pick with count

### ISSUE THREAD

**Issue by theusualcoder** [victorquinn/chancejs#205] opened 2015-09-17 05:09 UTC
Pick with count currently returns an array when count > 1.
When count is 1, it returns a single element, same as calling without a count.

For consistency, when count is present it should always return an array.
When count is 1 it should return an array containing a single element.

**Comment by oliversalzburg** [comment] 2015-09-17 10:39
Duplicate of https://github.com/victorquinn/chancejs/pull/174

**Comment by theusualcoder** [comment] 2015-09-18 07:48
I was thinking something simpler as in
https://github.com/victorquinn/chancejs/pull/206

Borrowed some of your error checking code.

**Comment by oliversalzburg** [comment] 2015-09-18 07:59
I actually wanted to write a new PR (good to see that you were up to the job sooner than me :)), where I wanted to leave `pick` as it is right now, to ensure backwards compatibility.

Maybe a new function should be added (`select` maybe?) that *always* returns an array. What do you think?

**Comment by theusualcoder** [comment] 2015-09-18 08:21
Ah, I see.  Then we could add two new functions `pickone` (returns single element) and `pickset` (returns array), where the use is unambiguous by name.  This way we could keep `pick` as is for backwards compatibility but in deprecated state before removing it sometime in the future.

**Comment by oliversalzburg** [comment] 2015-09-18 09:27
That sounds great to me. Maybe @victorquinn has some thoughts as well?

**Comment by theusualcoder** [comment] 2015-10-01 08:13
Done. Hope I did not miss anything. Care to review it?

**Comment by victorquinn** [comment] 2015-10-01 11:50
Looks great! Sorry, appears I missed the discussion here but it's good and I dig the outcome.

**Closed by victorquinn** 2015-10-01 11:50 UTC

**Comment by rosshadden** [comment] 2015-11-04 16:47
I think the new `pickone` and `pickset` methods are entirely unnecessary.  Why not just always return an array when `count` is passed?  Even when it's `0` or `1`.  This would make the API much more simple and consistent.
